apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata: 
      name: mavenapppod
      labels:
        app: mavenapp
    spec:
      containers:
      - name: mavencontainer
        image: nickregistry/maven-web-application:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
spec:
  type: NodePort
  selector:
    app: mavenapp
  ports:
  - port: 80
    targetPort: 8080
